application:
  title: IMusic
  admin_title: Admin IMusic
  admin: admin
user:
  name:
    max_length: 50
track:
  featured_list: 3
album:
  featured_list: 8
category:
  featured_list: 8
  name:
    max_length: 30
artist:
  featured_list: 4
min_friendly_token: 0
max_friendly_token: 20
omniauth:
  facebook: facebook
  google_oauth2: google_oauth2
